version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379

  redis-browser:
    image: obytes/redis-browser:latest
    command: --url redis://redis:6379
    ports:
      - 4567:4567
    depends_on:
      - redis